name: sincro_app_flutter
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Pacote para localização do app (datas, etc.)
  flutter_localizations:
    sdk: flutter

  google_fonts: ^6.3.2
  cupertino_icons: ^1.0.8

  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3

  google_sign_in: ^7.2.0
  reorderable_grid_view: ^2.2.8
  
  table_calendar: ^3.2.0
  collection: ^1.19.1

  flutter_staggered_grid_view: ^0.7.0

  rxdart: ^0.28.0

  firebase_ai: ^3.4.0

  equatable: ^2.0.5

  firebase_app_check: ^0.4.1+1

  cloud_functions: ^6.0.3

  uuid: ^4.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-VariableFont_opsz,wght.ttf